### ISSUE TITLE
Auto publish component library

### ISSUE THREAD

**Issue by ricardovdheijden** [workfloworchestrator/orchestrator-ui#110]
Setup a Github workflow that publishes the component library.

Creating a git tag would be the trigger
Version numbering is currently not automated and we are using a postfix "-alpha..". In this story assume the developer manually updates the version number in a PR.

Our current published versions:
https://www.npmjs.com/package/@orchestrator-ui/orchestrator-ui-components?activeTab=versions

**Comment by acidjunk** [comment]
#169 handles this.

It uses changeset https://github.com/changesets/changesets to keep track of changes and decide which "sub"packages should be published. It also keeps track of the changelog in way that let's collaborator's prepare a release.

**Comment by ricardovdheijden** [comment]
In the current state it is possible to just take the app from the mono repo and can run without any changes to the project. That means * as version is valid in package.json. Though * is not recommended for a real consumer of our packages in case we introduce breaking changes. 

When using * and refresh the versions in yarn.lock file run the command:
`yarn upgrade <packageName>`, eg `yarn upgrade @orchestrator-ui/eslint-config-custom`

**Comment by ricardovdheijden** [comment]
Block-reason: need to discuss with team how to implement the GithubAction for publishing to NPM. The current workflow needs a direct commit/push to main, which is suboptimal and currently blocked by branch protection rules.
The plugin "changesets" perfoms changes on package.json files when processing a changeset -- this could be done through a automated PR
However, while performing the publish command it creates a tag that needs to be pushed. -- its unclear how we can make this work with te branch protection rules enabled.

**Comment by ricardovdheijden** [comment]
Example implementing this: https://github.com/mattpocock/pkg-demo (with a video https://www.youtube.com/watch?v=eh89VE3Mk5g)
