### ISSUE TITLE
Implement the Subscription detail page for SURF and remove SURF specific code from lib after that

### ISSUE THREAD

**Issue by acidjunk** [workfloworchestrator/orchestrator-ui#120]
Now the subscription detail page fetched external system data from IMS; which is SURF specific.

This can be removed from the example app when the Subscription details page is implemented in SURF:

- [ ] copy the subscription details page to the SURF specific GUI
- [ ] remove externalData/IMS fetching from the lib

**Comment by hanstrompert** [comment]
Will revisit organisation specific features at a later stage.
