### ISSUE TITLE
Naming convention

### ISSUE THREAD

**Issue by ricardovdheijden** [workfloworchestrator/orchestrator-ui#146]
- [x] Determine a proper naming convention of de exposed components and types from the lib

  - Prefix every exportable component with WFO
  - Postfix all toplevel pages with Page

- [x] Create ADR on naming conventions in mkdocs/docs/adrs
- [x] Apply to repository

**Comment by acidjunk** [comment]
During a discussion in slack; the prefix "WFO" for workflow orchestrator was selected.

So: WFOSubscriptionTable WFOSubscriptionDetailPage could be names in the lib
