### ISSUE TITLE
Process detail page: implement top section

### ISSUE THREAD

**Issue by wouter1975** [workfloworchestrator/orchestrator-ui#224]
Following the design, implement the top section describing the process:

![Image](https://github.com/workfloworchestrator/orchestrator-ui/assets/83226590/3b01fa93-6e3a-408e-85a4-edf7d6eeff03)

- [x] create skeleton page
- [x] Use breadcrumb approach similar to subscription detail page, use workflow key for initial input form, or use the process uuid as the last breadcrumb
- [ ] Use the workflow Description (see meta data page) as the header title
- [x] Show the applicable action buttons following the business rules
  - [ ] Retry (if process in state failed) --> REST call, see v1 app
  - [ ] Abort (if process in state failed) --> REST call, see v1 app
 
In the process overview bar add the following data:
- [x] Status
- [x] Started by (this is Reporter or the creator, not Assignee)
  - [ ] ~~format the `urn:collab:person:surf.nl:huism002` to only show the last part, `huism002` --> this is SURF specific, may consider skipping this for now~~
- [x] Customer (this is a new field not shown in design)
- [x] Current step
- [x] Started on
- [x] Last update (last modified)
- [x] Related subscriptions shows all subscriptions found in the processess_subscriptions table, the subscription description is show with a link to the subscription detail page.

**Comment by DutchBen** [comment]
Feedback version: https://ui-gh-ruben-floris-test.test.automation.surf.net/processes/7f00a75e-c465-4357-8daf-8c68b71544d6

**Comment by DutchBen** [comment]
These improvments are added after review by @wouter1975 
- Fontsize 'base' is to big, changed to 'm'
- Functionality is added where if the display date matches todays date only time will show, otherwise its date time .
- Related subscriptions descriptions are shown with a link to their detail pages
