### ISSUE TITLE
Implement time conversion to local machine time and date or time detail

### ISSUE THREAD

**Issue by wouter1975** [workfloworchestrator/orchestrator-ui#232]
Backend sends timestamps in ISO format (2023-07-25T08:43:57.383925+00:00). Frontend should show the time/date in local timezone (system time / browser).

Apply this in the whole app 

* On detail page add the timezone.

* On listpages (in tables) just show the time without timezone.
  - [ ] Show only the time when "today"
  - [ ] Show only the date when "not today"

- Determine string format for detail view
- Determine string format for clipboard value

**Comment by ricardovdheijden** [comment]
![Image](https://github.com/workfloworchestrator/orchestrator-ui/assets/20791917/f910109b-9d49-40f7-a8d7-4a133ccf9a39)

Using the browsers language settings it is possible to determine the locale of the user
