### ISSUE TITLE
Add Dropdown menu when clicking New process button

### ISSUE THREAD

**Issue by wouter1975** [workfloworchestrator/orchestrator-ui#276]
Use the design as leading design:

![Image](https://github.com/workfloworchestrator/orchestrator-ui/assets/83226590/8d30f845-14c3-4a06-bac9-f20787c0c7c6)

- [x] Open a modal with a dropdown component filled with all available product instances for which a create workflow exists. 
- [x] Clicking a product instance from the dropdown will launch the new process detail page an start the workflow for the selected product.
- [x] the modal should consist of a vertical scroll function
- [x] the modal should support a search input field, to filter the list of products

**Decision: let's rename new process to `New subscription`**

**Comment by ricardovdheijden** [comment]
Wating for backend to support to filterBy "CREATE" target

**Comment by wouter1975** [comment]
@ricardovdheijden Looks good! I see it is already merged.

In the dropdown the description can do without the Create... It makes it a bit more concise, as some of the descriptions are a bit long (maybe some cleanup needed in the product description as well).
