### ISSUE TITLE
Update card component on `Configuration` tab on subscription detail page

### ISSUE THREAD

**Issue by wouter1975** [workfloworchestrator/orchestrator-ui#282]
- [x] the product block `cards` are not shown in the same sorted order as the tree, but are added on top. Please change this that when making a product block visible it is inserted  at the right place.

![Image](https://github.com/workfloworchestrator/orchestrator-ui/assets/83226590/6543073a-6d4c-4309-ae4e-5e9d3030672b)

- [x] Update card component to include the `hide details/show details` option 
  - [x] default setting is to hide details (this link `show details` is visible on card)
- [x] Limit details on the product block card
  - [x] by default hide:
      - [x] empty rows (resource type with no value)
      - [x] `title`
      - [x] `name`
      - [x] `subscription_instance_id`
      - [x] `owner_subscription_id`
        * for example ESI contains no rows by default, as it does not have any resource types
  - [x] when show details is clicked, show:
    - [x] subscription_instance_id
    - [x] owner_subscription_id
- [x] use gray background for PB card component
- [x] add PB icon --> can be moved to separate ticket for `R2`

Added by Rene:
- [ ] Move inline styles to styles.ts

## Add navigation links
- [ ] ~add a button to show all product blocks~ --> see #328

**Comment by acidjunk** [comment]
Changes, regarding specs:

- made ownSubscription a text when pointing to self. A link when pointing to other sub
- don't hide empty block
- fixed a bug which hided boolean resource types
