### ISSUE TITLE
Process detail page loose ends

### ISSUE THREAD

**Issue by DutchBen** [workfloworchestrator/orchestrator-ui#318]
This tickets is to fix the last missing features of the process detail page. They are
- [x] timelinesteps, only count failures
- [x] scroll into views does not work perfect -- add a wait.
- [x] Flip meaning of Hidden Keys: ON shoould show the keys and OFF should hide them
- [x] Remove full screen from code-block in steps
- [x] Polling: after completing a form and being on the processDetail page the stepCards do not update (timeline is)
- [x] for the first step in the process use the play icon instead of the settings icon, as proposed in design
- [ ] ~Pending step: live time count based on time stamp previous step~
- [x] Add `View options` button TODO: Clarify
  - [x] expanded to choose `Raw JSON data` and `Hidden keys`
    - [x] implement `Raw JSON data` by hiding the step card component, and just stitch all steps states as one json blob.
      - [x] use the same grey design of the step state with the expand and copy functions
      - [ ] ~like Github, new tab with raw JSON~
      - [ ] ~Different from design: raw JSON is not a toggle but a button on the same bar.~
    - [x] implement `Hidden keys` for the card component view, similar as in current GUI.

Skipped:
- [ ] ~Create a 'Expand all' and a 'Collapse all' link. The 'Expand all' link is disabled when all details are expanded, the 'Collapse all' is disabled when all details are collapsed (Original requirement: Implement a toggle function, thus after clicking Expand all, the link is changed to Collapse all with the action to collapse all step cards)~
- [ ] ~introduce polling. https://dev.to/dailydevtips1/automatically-refetching-with-react-query-1l0f~ -- https://github.com/workfloworchestrator/orchestrator-ui/issues/314
- [ ] ~Delta view for modify workflows. << Perhaps an other ticket~

https://projects.invisionapp.com/share/MW134V4MHPB7?hideLogo=true#/screens/471562378

![Image](https://github.com/workfloworchestrator/orchestrator-ui/assets/83226590/0eb4bb03-7765-4bf3-9276-abafbee54c40)

**Comment by ricardovdheijden** [comment]
Updated the scope of this story. Some items got removed (strike trough)

**Comment by ricardovdheijden** [comment]
![image](https://github.com/workfloworchestrator/orchestrator-ui/assets/20791917/1971c14f-f3be-4a52-b357-fef6e2d7195b)

When a form redirects the user to a processDetail page, the polling mechanism keeps fetching the latest data. All components are getting updated except the steplist

**Comment by wouter1975** [comment]
@ricardovdheijden, minor improvement, would be good to hide the `collapse all` / `expand all` toggle when the `raw json` is presented.
