### ISSUE TITLE
Confirm/Cancel dialog modal

### ISSUE THREAD

**Issue by DutchBen** [workfloworchestrator/orchestrator-ui#325]
*What*
Implement a confirm/cancel dialog that handles questions that might be asked during form execution

*Why*
The form module in V1 had a modal that can trigger confirmation dialogs based on questions that are provided as part of the response from the endpoints that use pydantic forms. V2 misses this functionality. I have not seen any designs for dialogs. We can either use the same setup as the Toast messages, take what's in V1 and slightly modify it to match V2 or request a proper design.

*Acceptance*
The app shows confirmation dialog modals that display the questions posed by the pydantic form endpoints or a default submit/cancel modal when no specific question is supplied

**Comment by acidjunk** [comment]
Except for the forms; the V1 has confirm dialogs in a couple of places:
- abort and retry of process
- some of the actions that can be triggered from the tables
- CIM

**Comment by ricardovdheijden** [comment]
Resolved in #435
