### ISSUE TITLE
Add `Subscription delta` for modify workflows

### ISSUE THREAD

**Issue by wouter1975** [workfloworchestrator/orchestrator-ui#329]
After a modify workflow has been run or if halfway the WF failed, it can be quite useful to see what the actual modification was. By performing a deep-diff on the subscription with the __old_subscriptions__ and presenting it in a gitlab view (- and + highlighting) it will become instantly clear what the change comprised.

* The delta view is available on the process detail page for processes with the workflowTarget=MODIFY.
* Not available for processes with isTask=true

- [ ] only show subscription delta button, when workflowTarget=MODIFY
![Image](https://github.com/workfloworchestrator/orchestrator-ui/assets/83226590/5533eb30-8f34-4e2e-b57f-5eef655d8354)
- [ ] perform a deep diff on the subscription for which the WF is being run. Use the `subscription_id` from the `__old_subscriptions__` and compare with the subscription found in the last step state.
  * ensure that difference in sorting order is reflected as a delta
- [ ] to maximize the view width, open a modal and show the old and new subscription side by side, like presented in the design:

![Image](https://github.com/workfloworchestrator/orchestrator-ui/assets/83226590/7a39979f-6cb4-4688-ae85-b17f5f732b59)

- [ ] add header with the subscription_id and subscription description
- [ ] hide unchanged rows after 3 exact rows - like gitlab show the commit changes
- [ ] Don't include the copy or maximize buttons, that is nice to have R2+ features
- [ ] don't show the delta, as the side by side comparison is good enough, and is 100% clear on additions and deletions.

**When choosing a new library, discuss with other developers**

Use a library to present the delta in way that the additionas and deletions become instantly clear. Consider for example https://github.com/praneshr/react-diff-viewer#readme or https://github.com/otakustay/react-diff-view

**Comment by acidjunk** [comment]
Started with the first suggestion, but it;'s unmaintained:
https://github.com/praneshr/react-diff-viewer/issues/166
So switched to the fork which seems to be maintained.

React Diff Viewer uses [emotion](https://emotion.sh/) for styling. So very the
