### ISSUE TITLE
Reconsider default status filter choice on Task list page

### ISSUE THREAD

**Issue by wouter1975** [workfloworchestrator/orchestrator-ui#355]
Default tab filter should be implemented with the filterBy option of GraphQL. Use a filterBy string like: 
`-status:Completed|Aborted`

Benefit:
* the filterBy string is not visible in the search bar
* This allows the user to clear the search bar filter, and see all tasks. 
* All statusses are supported (including the new ones, like for example Awaiting callback, Resumed, etc)

- [ ] also use this filterBy mechanism at the workflows/processes list page

**Comment by wouter1975** [comment]
Probably better to change the Task list page into a page with a Tab component, with a completed|aborted Tab.

the data can be explicitly filtered by the GQL `filteredBy`

**Comment by acidjunk** [comment]
In progress #571
