### ISSUE TITLE
Implement settings page

### ISSUE THREAD

**Issue by hanstrompert** [workfloworchestrator/orchestrator-ui#54]
Implement settings page with:
- add bread crumb, 
- add `Settings` header 
- Flush settings
- Modify engine settings
- Worker type
  - If no celery workers are being by the orchestrator deployment, don't display this last `Worker Status` information "component".

Base content and action of this page on the existing orchestrator. The Worker type design is missing in Invision, but use the following illustration:

![image](https://github.com/workfloworchestrator/orchestrator-ui/assets/83226590/c702a8ba-9d6e-4fd1-b84e-5b13f62e456d)

Invision prototype:
- https://projects.invisionapp.com/share/MW134V4MHPB7?hideLogo=true#/screens 

Sketch file (inspect-element & downloadable)
- https://www.sketch.com/s/68008066-6d55-4e28-8ba9-cebb8489fc95

**Comment by acidjunk** [comment]
@hanstrompert : External?

**Comment by acidjunk** [comment]
Leftovers:

- cache flush isn’t complete 
- the engine status at the top of the page should also toggle (observer can’t be used because the queryProvider lives in the app and not in the lib: not sure how to handle this correctly yet)
- the last comment about Celery workers isn't implemented yet
