### ISSUE TITLE
Changing search bar string is not reflected in update table

### ISSUE THREAD

**Issue by wouter1975** [workfloworchestrator/orchestrator-ui#543]

**Comment by wouter1975** [comment]
If you edit the search bar string manually, and don't confirm with a `Return`, but click outside the inputbox, the search is not executed.

This results in strange behavior, like
* filter on `SPhasjhad`
* table is empty
* remove manually SP from search bar
* click outside the input box
* table remains empty.

**Comment by ricardovdheijden** [comment]
Reserved on my name since i am adusting the current search field

**Comment by ricardovdheijden** [comment]
The searchterm should be submitted when leaving the field (onBlur):
- click outside
- tab out
