### ISSUE TITLE
Cache invalidation and stale data

### ISSUE THREAD

**Issue by acidjunk** [workfloworchestrator/orchestrator-ui#545]
The default behaviour for react query is to show data from the cache (if avail) + do a refetch.

This should show data, which could be old: but when the fetching is done the new data should be visible.

```
const queryClientConfig: QueryClientConfig = {
    defaultOptions: {
        queries: {
            staleTime: 1 * 60 * 60 * 1000,
            cacheTime: 5 * 60 * 60 * 1000,
            refetchOnWindowFocus: true,
            keepPreviousData: true,
        },
    },
};
```

The keepPreviousData -> throws roet in the food.

This was added to give the tables a more smooth loading experience. But this should be done in the hooks that fetch query data instead of the root setting for react query. Luckily query options can easily be added for individueel cases.

This is probably also the root cause for #542

**Comment by acidjunk** [comment]
With this: an updated  subscription note (and the complete subscription detail info) is immediately visible:

const queryClientConfig: QueryClientConfig = {
    defaultOptions: {
        queries: {
            // staleTime: 1 * 60 * 60 * 1000,
            cacheTime: 5 * 60 * 60 * 1000,
            refetchOnWindowFocus: true,
            // keepPreviousData: true,
        },
    },
};

**Comment by ricardovdheijden** [comment]
Discussed in meeting: remove the staleTime and the keepPrevious. The tables might not work nice anymore -- they start showing `loading` when browsing between pages -- try to handle these situations by adding a skeleton
