### ISSUE TITLE
implement metadata/products list page

### ISSUE THREAD

**Issue by hanstrompert** [workfloworchestrator/orchestrator-ui#55]
Implement the product tab on the metadata page according to design using the GraphQL endpoint created in https://github.com/workfloworchestrator/orchestrator-core/issues/237. If the metadata page does not exist yet then create that page. Use the generic table component to implement this page. Do not implement actions at this stage, so no Edit, View or Delete.

![image](https://github.com/workfloworchestrator/orchestrator-ui/assets/83226590/4599d533-d83e-4d01-999f-d808aba28a32)

When clicking on the left menu item `Metadata` the first menu item is shown and highlighted (both in left menu bold text and the tab component). The url of this page should be .../metadata/products

- [ ] Add breadcrumb
- [ ] Add `Metadata` as header
- [ ] Tab component with products, productblocks, resource types, fixed inputs, workflows
- [ ] fill table with data and use either local storage/app default  to show columns/number of rows. 
  - [ ] none of the values are clickable
  - [ ] add sorting and filtering as available in subscription list page
  - [ ] no actions on data is required
  - [ ] the product blocks column should include all product blocks (only unique, no duplicates) used. Current orchestrator GUI only shows 1 product block.
 
Invision prototype:
- https://projects.invisionapp.com/share/MW134V4MHPB7?hideLogo=true#/screens

Sketch file (inspect-element & downloadable)
- https://www.sketch.com/s/68008066-6d55-4e28-8ba9-cebb8489fc95

**Comment by acidjunk** [comment]
@Georgi2704 is working on this in #58

**Comment by acidjunk** [comment]
This is blocked for now; we are implementing a super re-useable table; currently testing it for the subscriptions page.
