### ISSUE TITLE
Leave-page-modal activates the 'leave' action when pressing escape

### ISSUE THREAD

**Issue by ricardovdheijden** [workfloworchestrator/orchestrator-ui#557]
Leave-page modal is a special variant of the confirm modal where the `cancel` and `confirm` actions are swapped.
![image](https://github.com/workfloworchestrator/orchestrator-ui/assets/20791917/0da1eebd-d571-4f5f-9604-ac111fee443d)

Pressing escape on the keyboard does trigger the cancel action

**Comment by wouter1975** [comment]
@ricardovdheijden, I had expected that the escape would keep trigger the stay action.
