### ISSUE TITLE
fix server side rendering for EUI grid component

### ISSUE THREAD

**Issue by hanstrompert** [workfloworchestrator/orchestrator-ui#56]
Currently server side rendering is disabled on the EUI grid component. Please investigate and implement possible fix. Either @acidjunk or @ricardovdheijden can supply more information on the issue.

**Comment by acidjunk** [comment]
Did some reading: server sided rendering is nice for SEO and almost static pages.
You can't prefetch subscriptions when building the GUI.

We introduced a component to mostly turn it off for now.

**Comment by acidjunk** [comment]
I now understand that Hans want to investigate the possibilities. So re-opened.
