### ISSUE TITLE
Troubleshoot production

### ISSUE THREAD

**Issue by wouter1975** [workfloworchestrator/orchestrator-ui#577]
- [x] Check that all endpoint work as expected, not all clients seem to pass the token.

- [ ] add username from auth in `Welcome` message on startpage
- [x] Not authenticated 403 error
  - [x] create new task - eg `clean_up_old_tasks`
  - [x] create new subscription - eg `create_ip_peer_group`
  - [x] open subscription detail page: https://orchestrator.automation.surf.net/api/subscriptions/workflows/619e5b90-4e0c-4d07-927d-3dd0d7954f05
  - [x] Action menu on a subscription detail page is empty
![Image](https://github.com/workfloworchestrator/orchestrator-ui/assets/83226590/8a336d85-4df3-4745-86a9-ae50685820ba)

**Comment by DutchBen** [comment]
The username seems like an issue that is unrelated to passing tokens and occurs on dev aswell. In the code it gets the username from the session but it looks like it's always Georgi. I propose a separate ticket for that.
