### ISSUE TITLE
Search and filter function for generic table

### ISSUE THREAD

**Issue by wouter1975** [workfloworchestrator/orchestrator-ui#76]
The search input box placed just above the table shall be the source of truth for the filter status of the table. 

<img width="1170" alt="image" src="https://github.com/workfloworchestrator/orchestrator-ui/assets/83226590/41ec9c8b-906f-4d90-ad58-f1c88802f682">

Examples of a valid input string:

```customerName:'Open universiteit' productTag:LP 50Mbits```

- [x] Manual input followed by pressing `Enter` shall refresh the content of the table
- [x] The column header is followed by a `:` indicates that this column shall be filtered on the supplied string (eg productTag:LP should filter the subscription table on LP products only)
- [x] Search string without a header field shall be interpreted as a global search in the TSV column
- [x] Multiple filter and search (TSV column) actions shall be supported. The filter should support AND and OR, default interpretation of a space is the AND operator and starts a new filter/search term
  - [x] OR should only be supported to support multiple per column. Filtering on multiple columns is always an AND.
- [x] String containing spaces require double quotes (edited, was 'single quotes')
- [x] Search and filter shall not be case sensitive

**Comment by ricardovdheijden** [comment]
WIP in branch:
feature/table-filter

After entering a query in the searchbar, the query appears in the URL.
Still need to pick the fields out of the queryText OR from the converted Elasticsearch Query DSL object to populate the filterBy parameter in the graphql call to backend

**Comment by acidjunk** [comment]
Currenttly it's only possible to do a OR inside a field: e.g. productTag = 'L2VPN' | 'L3VPN'

So not over fields

**Comment by wouter1975** [comment]
That is ok, as the OR operator support is only required to support multiselect per column, updated the original text to limit the OR to just 1 column.

**Comment by ricardovdheijden** [comment]
EuiSearchBar does not support to be set "invalid", might consider to change to EuiFieldSearch:

`<EuiFieldSearch
                placeholder="Search..."
                onSearch={(e) => setFilterQuery(e)}
                isClearable
                defaultValue={filterQuery}
                fullWidth
                isInvalid={queryContainsInvalidParts}
            />`
