### ISSUE TITLE
Implement tab component for subscription list page

### ISSUE THREAD

**Issue by wouter1975** [workfloworchestrator/orchestrator-ui#77]
Add the gitlab-style Tab component to the subscription list page. Changing the tab will trigger a reload of the subscription table. The URL shall also change, which includes an tab index (or name of the tab to make it better readable), so the URL can be used and shared with others.

![image](https://github.com/workfloworchestrator/orchestrator-ui/assets/83226590/06dd7653-c8fe-4de0-83a0-6861f41779c8)

Loading the subscription list page shall default to the `Active` tab, only 1 subscriptions page is used.

Implement both tabs with appropriate presets: 
* tab1: filter on `active` subscriptions
* tab1: filter on `terminated` subscriptions
* tab3: filter on `transient` --> all other states like `initial` `provisioning` `migrated`
* tab4: filter on `all`

Note that the following state is "sticky" when changing tabs within this subscriptions list page:
* number of rows 
* search input bar
* sorting order of column
* visible columns

To discuss: page number can possible be sticky, but can result in unexpected behavior. Maybe default back to first page?

**Comment by ricardovdheijden** [comment]
Done. SURF specific version is updated and deployed
