### ISSUE TITLE
Implement Resource Types page under Metadata

### ISSUE THREAD

**Issue by wouter1975** [workfloworchestrator/orchestrator-ui#87]
implement the Resource Types page according to the design as shown below:

- [x] update breadcrumb when navigating to this page from left menu or from tabcomponent
- [x] fill table with data and use either local storage/app default  to show columns/number of rows. 
  - [x] none of the values are clickable
  - [ ] add sorting and filtering as available in subscription list page
  - [x] no actions on data is required

The invision design does not specify the look and feel of this page but the "old" implementation  needs to be expanded with some extra columns:
<img width="1874" alt="image" src="https://github.com/workfloworchestrator/orchestrator-ui/assets/83226590/b539d701-5e23-40d9-b796-7740a856f93b">

Please include the following columns:
* Resource type
* Description
* Product Blocks 
  * can be multiple product blocks. Use the Blue shading as used on other pages 
* Resource Id

**Comment by Georgi2704** [comment]
For querying the product blocks for each resource type, the graphql doesn't have the functionality so I leave it blank

**Comment by wouter1975** [comment]
@tjeerddie, do you if the addition of product blocks under resource types is on the backlog of the backend?
