### ISSUE TITLE
Implement process list page

### ISSUE THREAD

**Issue by wouter1975** [workfloworchestrator/orchestrator-ui#91]
Implement the process list page.

Similar to the subscription list page, this page has 2 viewing mode. Either Active processes or completed processes. The difference with the subscription list page is that the column voor Active and Completed processes are typically different. Thus this implies that we cannot use the same column defaults defined in the app, nor store the user table preference in one set of variables. 

The default page start with the `Active process` activated, thus clicking on `Processes` menu item of the left hand menu will load the `Active processes` in the table.

Data loading for the tables are based on the Status filtering:

* The status for Active are: `Created`, `Running`, `Suspended`, `Waiting`, `Failed`, `Resumed`
* The status for `Completed` are: `Completed`

The processes endpoint can be used and only list on the Processes page are processes which are **not** created by `SYSTEM`.

- [x] add a state for an empty table for both Active and Completed (applicable for first/initial use).
- [x] follow column structure according to design.
- [x] Load page with defaults from app, or if local storage has applicable ActiveProcessesTableSetting/CompletedProcessesTableSetting use these.
- [x] Any column can be sorted/filtered as developed for the subscription list page #76 and #81 

**Default column settings and order for `Active Processes`**
workflow --> include a link to the process detail page
last step
status
target
tag
product - **hidden**
customer - **hidden**
abbrev
subscription --> include a link to the subscription detail page
creator - **hidden**
assignee - **hidden**
pid - **hidden**
started
modified

**Default column settings and order for `Completed Processes`**
workflow --> include a link to the process detail page
last step - **hidden**
status - **hidden**
target
tag
product - **hidden**
customer - **hidden**
abbrev
subscription --> include a link to the subscription detail page
creator - **hidden**
assignee - **hidden**
pid - **hidden**
started - **hidden**
modified

**Comment by ricardovdheijden** [comment]
Some DOD items are blocked due to missing functionality in backend:
- [ ] Sorting: backend change is needed to match the colum names with the data (for now hardcoded)
- [ ] Missing columns: target, tag, customer abbrev -- waiting for backend change to add these
- [ ] The lastStep prop: is implemented in frontend, but backend returns always 'null' as value
